site_name: Dart Course
nav:
  - Home: index.md
  - Modules:
      - Module 1 - Introduction to Dart: modules/module1.md
      - Module 2 - Basic Data Types and Variables: modules/module2.md
      - Module 3 - Control Structures: modules/module3.md
      - Module 4 - Functions: modules/module4.md
      - Module 5 - Collections: modules/module5.md
      - Module 6 - Class and Objects: modules/module6.md
      - Module 7 - Exception Handling: modules/module7.md
      - Module 8 - Asynchronous Programming: modules/module8.md
      - Module 9 - Files and Streams: modules/module9.md
      - Module 10 - Packages and Dependencies: modules/module10.md
  - Flutter:
      - Introduction: flutter/introduction.md
      - Module 1 - Getting Started with Flutter: flutter/module1.md
      - Module 2 - Building Flutter UIs:
          - Introduction: flutter/module2.md
          - Lesson 1: flutter/module2/2.1.md
          - Lesson 2: flutter/module2/2.2.md
          - Lesson 3: flutter/module2/2.3.md
          - Lesson 4: flutter/module2/2.4.md
          - Lesson 5: flutter/module2/2.5.md
      - Module 3 - Managing State in Flutter:
          - Lesson 1: flutter/module3/3.1.md
          - Lesson 2: flutter/module3/3.2.md
          - Lesson 3: flutter/module3/3.3.md
          - Lesson 4: flutter/module3/3.4.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences
