site_name: Dart Course
nav:
  - Home: index.md
  - Modules:
      - Module 1 - Introduction to Dart: modules/module1.md
      - Module 2 - Basic Data Types and Variables: modules/module2.md
      - Module 3 - Control Structures: modules/module3.md
      - Module 4 - Functions: modules/module4.md
      - Module 5 - Collections: modules/module5.md
      - Module 6 - Class and Objects: modules/module6.md
      - Module 7 - Exception Handling: modules/module7.md
